<?php

/**
 * Print a markdown one-pager listing every pack node — what to click,
 * which license, whether the raw file is attached.
 *
 * Run via:
 *   ddev drush scr scaffold/print-pack-checklist.php
 *
 * Output: a markdown table to stdout. Paste into a working doc or
 * pipe to a file:
 *   ddev drush scr scaffold/print-pack-checklist.php > /tmp/checklist.md
 *
 * Each row shows:
 *   - whether the pack has its raw_file attached yet (✅ / ⬜)
 *   - the pack's title + source URL
 *   - the declared license tier
 *   - the child asset count + slot binding(s)
 *
 * After clicking through to download a pack's raw .zip / .glb, run:
 *   ddev drush scr scaffold/attach-pack-file.php -- <nid> <local-path>
 * to ingest the file into Drupal.
 */

declare(strict_types=1);

$packs = \Drupal::entityTypeManager()
  ->getStorage('node')
  ->loadByProperties(['type' => 'pack']);
$assets = \Drupal::entityTypeManager()
  ->getStorage('node')
  ->loadByProperties(['type' => 'asset']);

// Group asset children by pack id.
$childrenByPack = [];
foreach ($assets as $a) {
  $packId = $a->get('field_asset_pack')->target_id;
  $childrenByPack[$packId][] = $a;
}

// Sort packs by license tier (CC0 first, then CC-BY, then unverified).
$tierOrder = ['CC0' => 1, 'CC-BY' => 2, 'CC-BY-SA' => 3, 'CC-BY-NC' => 4];
uasort($packs, function ($a, $b) use ($tierOrder) {
  $la = $a->get('field_pack_license')->entity?->label() ?? '?';
  $lb = $b->get('field_pack_license')->entity?->label() ?? '?';
  $oa = $tierOrder[$la] ?? 99;
  $ob = $tierOrder[$lb] ?? 99;
  return $oa <=> $ob;
});

echo "# Pack acquisition checklist\n\n";
echo "Auto-generated by `scaffold/print-pack-checklist.php`. ";
echo "Click each pack's source URL, download the raw archive, then run:\n\n";
echo "```\n";
echo "ddev drush scr scaffold/attach-pack-file.php -- <nid> <local-path>\n";
echo "```\n\n";

echo "| ⬜/✅ | nid | License | Pack | Source | Slot(s) |\n";
echo "| --- | --- | --- | --- | --- | --- |\n";

foreach ($packs as $p) {
  $hasFile = !$p->get('field_pack_raw_file')->isEmpty();
  $marker = $hasFile ? '✅' : '⬜';
  $license = $p->get('field_pack_license')->entity?->label() ?? '?';
  $source = $p->get('field_pack_source_url')->uri ?? '';
  $sourceLink = $source ? "[link]($source)" : '—';

  $children = $childrenByPack[$p->id()] ?? [];
  $slots = [];
  foreach ($children as $c) {
    $slot = $c->get('field_asset_slot')->entity?->label() ?? '?';
    $slots[$slot] = TRUE;
  }
  $slotsList = $slots ? implode(', ', array_keys($slots)) : '—';

  // Mark multi-slot packs.
  $titlePrefix = count($slots) > 1 ? '★ ' : '';

  echo sprintf(
    "| %s | %d | %s | %s%s | %s | %s |\n",
    $marker,
    $p->id(),
    $license,
    $titlePrefix,
    $p->label(),
    $sourceLink,
    $slotsList,
  );
}

echo "\n★ = pack fills multiple slots (one acquisition covers them all).\n";

$pending = 0;
foreach ($packs as $p) {
  if ($p->get('field_pack_raw_file')->isEmpty()) {
    $pending++;
  }
}

echo sprintf("\n**Status:** %d / %d packs acquired.\n", count($packs) - $pending, count($packs));
echo "\n## Recommended pull order\n\n";
echo "1. **Quaternius Ultimate Stylized Nature Pack** — covers oak-stylized + forest-scenery in one pull.\n";
echo "2. **KayKit Forest Nature Pack** — covers forest-scenery (and possibly sapling-figure) in one pull.\n";
echo "3. **KayKit Adventurers** — clean sapling-figure candidate.\n";
echo "4. The rest are backups / variety.\n";
